// This file is auto-generated by set-env.js during the build process.
// Do not modify this file manually.
export const env = {
  NG_APP_API_URL: 'http://localhost:8080',
  NG_APP_CORE_API_URL: 'http://localhost:8080/api/core',
  NG_APP_INSPECCIONES_API_URL: 'http://localhost:8080/api/inspeccion'
};
