const fs = require('fs');
const path = require('path');

// Prioritize Angular prefix NG_APP_API_URL, fall back to API_URL or VITE_API_URL, and default to localhost:8080
const apiUrl = process.env.NG_APP_API_URL || process.env.API_URL || process.env.VITE_API_URL || 'http://localhost:8080';

const content = `// This file is auto-generated by set-env.js during the build process.
// Do not modify this file manually.
export const env = {
  NG_APP_API_URL: '${apiUrl}'
};
`;

const targetPath = path.join(__dirname, 'src/app/core/services/api.config.env.ts');

try {
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log(`[set-env] Generated environment config at ${targetPath} with URL: ${apiUrl}`);
} catch (error) {
  console.error('[set-env] Error generating environment config:', error);
  process.exit(1);
}
