const fs = require('fs');
const path = require('path');

// Read environment variables
const gatewayUrl = process.env.NG_APP_API_URL || process.env.API_URL || process.env.VITE_API_URL || 'http://localhost:8080';

// If they specify separate service URLs (for direct Railway deployments without Nginx), use them.
// Otherwise, append the standard gateway paths to the gateway URL.
const coreUrl = process.env.NG_APP_CORE_API_URL || `${gatewayUrl}/api/core`;
const inspeccionesUrl = process.env.NG_APP_INSPECCIONES_API_URL || `${gatewayUrl}/api/inspeccion`;

const content = `// This file is auto-generated by set-env.js during the build process.
// Do not modify this file manually.
export const env = {
  NG_APP_API_URL: '${gatewayUrl}',
  NG_APP_CORE_API_URL: '${coreUrl}',
  NG_APP_INSPECCIONES_API_URL: '${inspeccionesUrl}'
};
`;

const targetPath = path.join(__dirname, 'src/app/core/services/api.config.env.ts');

try {
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log(`[set-env] Generated environment config:`);
  console.log(`  - GATEWAY: ${gatewayUrl}`);
  console.log(`  - CORE: ${coreUrl}`);
  console.log(`  - INSPECCIONES: ${inspeccionesUrl}`);
} catch (error) {
  console.error('[set-env] Error generating environment config:', error);
  process.exit(1);
}
