export const COLOMBIA_DEPARTAMENTOS: { [key: string]: string[] } = {
  'Amazonas': ['Leticia', 'Puerto Nariño', 'El Encanto', 'La Chorrera', 'Tarapacá'],
  'Antioquia': ['Medellín', 'Envigado', 'Andes', 'Urrao', 'Jericó', 'Apartadó', 'Bello', 'Itagüí', 'Rionegro', 'Caucasia'],
  'Arauca': ['Arauca', 'Arauquita', 'Saravena', 'Tame', 'Fortul', 'Cravo Norte'],
  'Atlántico': ['Barranquilla', 'Soledad', 'Malambo', 'Sabanalarga', 'Baranoa', 'Puerto Colombia'],
  'Bolívar': ['Cartagena', 'Magangué', 'Turbaco', 'El Carmen de Bolívar', 'Arjona', 'Mompox'],
  'Boyacá': ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Villa de Leyva', 'Paipa', 'Puerto Boyacá'],
  'Caldas': ['Manizales', 'La Dorada', 'Riosucio', 'Chinchiná', 'Villamaría', 'Anserma'],
  'Caquetá': ['Florencia', 'San Vicente del Caguán', 'Puerto Rico', 'Belén de los Andaquíes', 'El Doncello'],
  'Casanare': ['Yopal', 'Aguazul', 'Tauramena', 'Paz de Ariporo', 'Monterrey', 'Villanueva'],
  'Cauca': ['Popayán', 'Santander de Quilichao', 'Puerto Tejada', 'Patía', 'Bolívar', 'Silvia'],
  'Cesar': ['Valledupar', 'Aguachica', 'Agustín Codazzi', 'Bosconia', 'El Copey', 'Curumaní'],
  'Chocó': ['Quibdó', 'Istmina', 'Condoto', 'Acandí', 'Bahía Solano', 'Tadó'],
  'Córdoba': ['Montería', 'Cereté', 'Sahagún', 'Lorica', 'Planeta Rica', 'Montelíbano', 'Tierralta'],
  'Cundinamarca': ['Bogotá', 'Fusagasugá', 'Facatativá', 'Chía', 'Zipaquirá', 'Soacha', 'Girardot', 'Mosquera', 'Funza'],
  'Guainía': ['Inírida', 'Barrancominas', 'San Felipe', 'Mapiripana'],
  'Guaviare': ['San José del Guaviare', 'Calamar', 'El Retorno', 'Miraflores'],
  'Huila': ['Neiva', 'Pitalito', 'Garzón', 'La Plata', 'Campoalegre', 'San Agustín'],
  'La Guajira': ['Riohacha', 'Maicao', 'Uribia', 'San Juan del Cesar', 'Manaure', 'Fonseca'],
  'Magdalena': ['Santa Marta', 'Ciénaga', 'Fundación', 'El Banco', 'Plato', 'Aracataca'],
  'Meta': ['Villavicencio', 'Acacías', 'Granada', 'Puerto López', 'Puerto Gaitán', 'San Martín'],
  'Nariño': ['Pasto', 'Ipiales', 'Tumaco', 'Túquerres', 'La Unión', 'Samaniego'],
  'Norte de Santander': ['Cúcuta', 'Ocaña', 'Pamplona', 'Villa del Rosario', 'Los Patios', 'Tibú', 'Chínacota'],
  'Putumayo': ['Mocoa', 'Puerto Asís', 'Orito', 'Sibundoy', 'Valle del Guamuez', 'Puerto Leguízamo'],
  'Quindío': ['Armenia', 'Calarcá', 'Tebaidá', 'Montenegro', 'Quimbaya', 'Salento'],
  'Risaralda': ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'Belén de Umbría', 'La Virginia'],
  'San Andrés y Providencia': ['San Andrés', 'Providencia', 'Santa Catalina'],
  'Santander': ['Bucaramanga', 'Lebrija', 'Girón', 'San Gil', 'Rionegro', 'Piedecuesta', 'Floridablanca', 'Barrancabermeja', 'Socorro', 'Barbosa'],
  'Sucre': ['Sincelejo', 'Corozal', 'San Marcos', 'Tolú', 'Sampués', 'Sincé'],
  'Tolima': ['Ibagué', 'Espinal', 'Melgar', 'Mariquita', 'Honda', 'Líbano', 'Chaparral'],
  'Valle del Cauca': ['Cali', 'Palmira', 'Buga', 'Tuluá', 'Cartago', 'Buenaventura', 'Jamundí', 'Yumbo', 'Caicedonia', 'Sevilla'],
  'Vaupés': ['Mitú', 'Carurú', 'Taraira', 'Pacoa'],
  'Vichada': ['Puerto Carreño', 'La Primavera', 'Santa Rosalía', 'Cumaribo']
};
